### ISSUE TITLE
Question about the SX operator

### ISSUE THREAD

**Issue by chynphh** [lifu-tu/ENGINE#3]
Hi, 
Why you replace the softmax function with  the exp function in  SX?
https://github.com/lifu-tu/ENGINE/blob/73a9d3846fb59b2296df1c99c93ee7f52ce088d6/fairseq/models/transformer.py#L735

https://github.com/lifu-tu/ENGINE/blob/73a9d3846fb59b2296df1c99c93ee7f52ce088d6/fairseq/criterions/inf_energy_loss.py#L163

**Comment by lifu-tu** [comment]
The input of the operator are the log probabilities in the implementation. After the exp function, the distribution vectors are computed.

**Comment by chynphh** [comment]
Thanks.
